Feat/125 문서를 작성한다.
woowacourse-teams/2020-6rinkers pull request #172
Opened 2020-08-28 07:44 UTC by toneyparky

README.md를 작성한다.

2020-08-29 12:57 UTC, KueNiYam approved these changes
안녕하세요, 토니 👍 
새로운 리드미가 아름답네요..!
추가할 것이라면, 문화나 철학같은 부분이 포함되면 조금 더 팀의 정체성을 나타낼 수 있을 것 같아요.

2020-08-29 16:17 UTC, ParkDooWon requested changes
문서를 예쁘게 잘 만들어주셨네요! 👍 
문서와 관련해서 코멘트 간단하게 남겼습니다. 확인해주시고 토니 의견 남겨주세요~~ :)

2020-08-29 16:17 UTC, ParkDooWon commented on README.md
>  - [@인스타그램 주소](https://instagram.com/cocktail_pick)
```suggestion
- [인스타그램 주소](https://instagram.com/cocktail_pick)
```
`@`를 의도적으로 넣은 것이 아니라면, 아래와 형식을 맞춰 `@`를 제거하고 `인스타그램 주소`라고 쓰는게 더 깔끔할 것 같아요!

2020-08-29 16:17 UTC, ParkDooWon commented on README.md
> +# :cocktail: 칵테일픽
여기나 더 적절한 곳에 서비스 URL(cocktailpick.com)을 함께 넣어두면 어떨까요?

2020-08-30 10:39 UTC, minuyim approved these changes
리드미 깔끔하게 작성해주셨네요.
수고하셨습니다.
딱히 피드백 드릴부분은 없습니다. Approve하겠습니다.

2020-08-31 02:57 UTC, ParkDooWon approved these changes
멋진 readme 입니다! 어프루브할게요!

2020-08-31 02:59 UTC, KimGyeong approved these changes
너무 야무져서 무릎을 탁 치고 Approve 하겠습니다~

2020-08-31 02:59 UTC, merged