Feat/112 회원정보 수정 기능을 구현한다.
woowacourse-teams/2020-6rinkers pull request #175
Opened 2020-09-08 08:36 UTC by KimGyeong

resolve: #112 
이메일은 변경하지 않고, 이름만 변경하게 구현했습니다.

변경된 이름이 바로 적용되지 않아 수정 후 새로고침하게 하였습니다.

![image](https://user-images.githubusercontent.com/18031638/92452846-8a707d00-f1f9-11ea-9120-2595cdb607e3.png)

2020-09-08 14:52 UTC, ParkDooWon requested changes
작곰! 회원정보 수정 기능 구현하느라 수고하셨습니다 :)
방학이 끝나자마자 pr이.. 👍 
몇 가지 코멘트 남겼어요. 확인하시고 필요한 부분 반영 부탁드려요!!
UserController에 대한 코멘트에 작곰의 생각을 남겨주시면 감사하겠습니다! :)

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
UserController에 대해서 API를 USER와 ADMIN이 모두 함께 쓰고있고, USER와 ADMIN에게 서로 다르게 제공되는 기능이 없다고 생각합니다. 그래서 계속 반복되는 `@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")`를 메서드 마다 붙이기보단 클래스에 `@RequestMapping("/api/user")`처럼 붙이는 것은 어떨까요?

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
그리고 혹시 ADMIN만 API를 사용할 수 있도록 하려면 메서드에 붙인 어노테이션을 더 우선순위로 두기 때문에 해당 메서드에 `@PreAuthorize("hasRole('ADMIN')")`만 붙여주면 됩니다. 그래서 전체적으로 클래스에 `@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")`를 붙이고, 특별한 경우에만 메서드에 `@PreAuthorize` 어노테이션을 붙이는 것이 더 좋지않을까하는 생각이 들어요. 메서드마다 붙는 중복되는 코드가 줄어드니까! :)

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
> +	@WithMockCustomUser
`@DisplayName` 어노테이션이 빠졌어요!

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
> +		mockMvc.perform(RestDocumentationRequestBuilders.put("/api/user/me")
```suggestion
		mockMvc.perform(put("/api/user/me")
```
UserControllerTest 안에서는 이미 `RestDocumentationRequestBuilders`만을 import해서 사용하고 있어서 굳이 명시하지 않아도 될 것 같아요! :)

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +			responseFields(
```suggestion
			requestFields(
```
UserController에서 updateCurrentUser 메서드는 `@RequestBody`만 있고, 반환하는 `@ResponseBody`는 없어서 `responseFields`를 `requestFields`로 수정해주셔야 할 것 같아요! :)

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +				fieldWithPath("name").type(JsonFieldType.STRING).description("접속한 user의 이름")
```suggestion
				fieldWithPath("name").type(JsonFieldType.STRING).description("변경할 user의 이름")
```
요청으로 '바뀔 이름'이 오는거니까 `변경할 user의 이름`같은 느낌으로 바꾸는 것이 어떨까요? 아니면 `요청한 user의 이름`?? 이름 짓기가 어렵네요.. 😢

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
> +	@Test
여기도 `@DisplayName` 넣어주세요! :)

2020-09-08 14:52 UTC, ParkDooWon commented on back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
> +			.isEqualTo(userUpdateRequest.getName());
```suggestion
		assertThat(user.getName()).isEqualTo(userUpdateRequest.getName());
```
코드가 길지 않아서 줄바꿈이 없어도 될 것 같아요!

2020-09-08 15:16 UTC, toneyparky approved these changes
저도 간단하게 리뷰를 남겨봤어요~

간만에 남기고 싶더라구요.
두강이가 꼼꼼하게 잘 남겨준 덕에 코드를 보기 수월했답니다~

수고했습니다! 저는 approve하겠습니다. 필요한 코멘트 반영 부탁드려요.

2020-09-08 15:16 UTC, toneyparky commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
괜찮은 방법이군요.
두강이의 방법을 반영해서 돌려보고 적용된다면 처리해보아요.

2020-09-08 15:16 UTC, toneyparky commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +			responseFields(
역시 API 문서의 대가 두강

2020-09-08 15:16 UTC, toneyparky commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +				fieldWithPath("name").type(JsonFieldType.STRING).description("접속한 user의 이름")
변경할 수정할 바뀔
골라골라~
🙂

2020-09-08 15:16 UTC, toneyparky commented on back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
> +			.isEqualTo(userUpdateRequest.getName());
```suggestion
		assertEquals(user.getName(), userUpdateRequest.getName());
```

요 메서드도 있지요😊

2020-09-08 15:16 UTC, toneyparky commented on front/src/component/mypage/ProfileDetail.js
> +  const [name, setName] = useState(user.currentUser.name);
오호 이래도 리코일에서 관리되는 user의 name에 반영이 되나보군요..!

2020-09-08 15:16 UTC, toneyparky commented on front/src/css/mypage/profile.css
> +    background-color: rgba(100, 100, 100, 0.1);
색상들을 상수화해두면 좋을 것 같지만.
자주쓰이는 색상들이 아니기에 넘어가도 좋습니다~

2020-09-08 16:04 UTC, ParkDooWon commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
제가 작곰 코드에서 이것저것 시도했을 때는 제대로 동작했습니다. (권한이 없는 경우엔 500 에러가 발생합니다.)

- 모든 메서드에 붙은 `@PreAuthorize~~`를 제거하고 클래스에만 `@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")` 붙인 경우
- 클래스에 `@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")`를 붙인 상태에서 메서드에 `@PreAuthorize("hasRole('ADMIN')")`와 `@PreAuthorize("hasRole('USER')")` 각각 붙인 경우
 -> 유저(관리자) 권한만 있는 경우를 확인하고 클래스의 어노테이션 보다 메서드가 우선한지 확인하기 위함

저는 이렇게 시도해봤어요. 작곰이 참고해서 의견 남겨주시면 감사하겠습니다!

2020-09-09 07:07 UTC, KimGyeong commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
`UserController` 같은 경우, 모든 사용자들이 사용할 수 있어야 하기에 `@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")` 를 클래스 자체에 붙이면 될 것 같아요. 좋은 피드백 고맙습니다 :)

2020-09-09 07:07 UTC, KimGyeong commented on back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
> +	@WithMockCustomUser
테스트 코드를 너무 오랜만에 짰나봐요... 추가하겠습니다 :(

2020-09-09 07:08 UTC, KimGyeong commented on back/src/test/java/com/cocktailpick/back/user/controller/UserControllerTest.java
> +		mockMvc.perform(RestDocumentationRequestBuilders.put("/api/user/me")
그렇네요! 제거하겠습니다

2020-09-09 07:08 UTC, KimGyeong commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +			responseFields(
네 제거하였습니다 :)

2020-09-09 07:09 UTC, KimGyeong commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +				fieldWithPath("name").type(JsonFieldType.STRING).description("접속한 user의 이름")
`수정할` 이 가장 와닿는 느낌이 드네요!

2020-09-09 07:58 UTC, minuyim requested changes
수정 기능 작성해주시느라 수고하셨습니다.
다만 현재 인수 테스트가 빠진 것 같네요. 추가해주시면 좋을 것 같습니다.

2020-09-09 07:58 UTC, minuyim commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
추가적인 의견으로 메서드 구분이 필요없다면 SecurityConfig에서 직접 설정해줘도 무방하다고 생각합니다.

2020-09-09 07:58 UTC, minuyim commented on back/src/main/java/com/cocktailpick/back/user/service/UserService.java
> +		user.setName(userRequest.getName());
개인적인 의견인데 User가 getter, setter만을 가지는 [빈약한 도메인 모델](https://www.martinfowler.com/bliki/AnemicDomainModel.html)인 것 같습니다. 레벨4 리팩토링 미션 중 이 빈약한 도메인 모델을 바꾸는 요구사항에 있기에 미리 메소드들을 바꿔보는 건 어떨까요?

2020-09-09 14:38 UTC, KimGyeong commented on back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
> +			.isEqualTo(userUpdateRequest.getName());
토니 피드백으로 수정할게요~

2020-09-10 16:40 UTC, minuyim reviewed
몇가지 코멘트 드렸습니다.

2020-09-10 16:40 UTC, minuyim commented on back/src/main/java/com/cocktailpick/back/user/domain/User.java
> +	public User updateUser(String name) {
사실 이부분은 메소드명을 좀 더 가독성을 올리는 게 좋다는 의견이었는데, 괜히 혼동을 드린것 같네요.

2020-09-10 16:40 UTC, minuyim commented on back/src/main/java/com/cocktailpick/back/user/service/UserService.java
> +		User updatedUser = user.updateUser(userRequest.getName());
아예 새로운 유저가 추가되는 걸 의도하신 건가요?

2020-09-11 00:22 UTC, ParkDooWon reviewed
추가적으로 put을 patch로 변경하셨네요!

2020-09-11 00:26 UTC, ParkDooWon approved these changes
추가적으로 put을 patch로 변경하셨네요!
[put과 patch의 차이점](https://www.baeldung.com/http-put-patch-difference-spring)
피드백 반영하신거 확인했습니다! 수고하셨어요 작곰 👍
approve 하겠습니다!

2020-09-11 04:29 UTC, KueNiYam commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
두강 멋져요~

2020-09-11 04:30 UTC, KueNiYam commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +			responseFields(
ㄷㄷ 저걸 어떻게 발견했지

2020-09-11 04:32 UTC, KueNiYam commented on back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
> +			.isEqualTo(userUpdateRequest.getName());
https://jongmin92.github.io/2020/03/31/Java/use-assertthat/

assertXXX 사용을 지양하자는 이야기가 있네요

2020-09-11 07:23 UTC, toneyparky commented on back/src/test/java/com/cocktailpick/back/user/service/UserServiceTest.java
> +			.isEqualTo(userUpdateRequest.getName());
이 부분에 대해서 저도 오늘 제이슨에게 피드백을 들었고 하나로 통일하는 편이 좋다는 이야기를 들었네요.
이미 구현이 되었다면 놔두고 아직 리팩토링을 할 예정이라면 다시 원상복귀해도 좋을 것 같아요.
귀찮게하여 미안합니다😢

2020-09-12 08:08 UTC, minuyim approved these changes
수고하셨습니다

2020-09-12 08:21 UTC, merged