Feat/113 회원 탈퇴 기능을 구현한다.
woowacourse-teams/2020-6rinkers pull request #188
Opened 2020-09-10 16:28 UTC by KimGyeong

resolve: #113 

현재 회원 탈퇴 후 동일한 이메일로 새로운 계정을 생성할 수 있게 했습니다.

회원 복구 기능을 추가하는 방법과 회원 탈퇴한 이메일로 새로운 계정을 만들지 못하는 방법 등 선택지가 있습니다.

의견을 주시면 좋을 것 같아요 :)

2020-09-10 22:01 UTC, toneyparky reviewed
몇가지 간단한 리뷰와 수정되면 좋을 사항들에 대해서 코멘트 남겼습니다.

수고했어요 작곰😋

작곰은 유저 관련된 로직의 아버지네요..!

수정 후 다시 요청주시면 approve 하겠습니다.

2020-09-10 22:01 UTC, toneyparky commented on front/src/component/mypage/ProfileDetail.js
> +          </a>
Link 태그를 사용해도 좋을 것 같아요!

```suggestion
          <Link to="/" onClick={userWithdraw} className="withdrawal-submit">
            회원 탈퇴
          </Link>
```

IDE 상에서 한게 아니고 깃헙 댓글 작성으로 수정한 부분이라 정확하지 않을 수 있습니다.

2020-09-11 00:30 UTC, ParkDooWon commented on back/src/main/java/com/cocktailpick/back/user/controller/UserController.java
> +	@PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
토니의 코멘트를 지금 반영해도 좋고, 작곰이 이전에 올린 회원 수정 기능이 dev에 머지되면 리베이스 하면서 변경해도 괜찮을 것 같아요 :)

2020-09-11 01:24 UTC, ParkDooWon requested changes
작곰이 올린게 git 채널에 떠서 들어와서 한번 보다가 몇 가지 수정하면 좋을 듯한 부분이 보여서 코멘트 남겨보아요.. 😄
확인해주시고 반영해주시면 감사하겠습니다! :)

2020-09-11 01:24 UTC, ParkDooWon commented on back/src/test/java/com/cocktailpick/back/user/docs/UserDocumentation.java
> +		return document("user/me",
```suggestion
		return document("user/delete",
```
위의 `findMe()`와 `deleteMe()` 메서드의 문서가 모두 generated-snippets 디렉토리 아래의 `user/me` 로 똑같은 파일에 만들어지고 있어요. 그래서 위의 `findMe()`의 파일명을 `user/find`로 바꾸고, `deleteMe()` 파일명도 `user/delete`와 같이 변경을 해줘야 정상적으로 문서가 만들어질 것 같아요. :)

2020-09-11 01:24 UTC, ParkDooWon commented on front/src/component/mypage/MyProfile.js
> +  const setCurrentUser = useSetRecoilState(userState);
이 부분은 저도 궁금했어요. props로 넘기는 것이 나은지, 사용하는 곳마다 선언을 해서 쓰는 것이 나은지..!
리코일을 사용하는 곳마다 선언을 직접 하면 코드가 늘어나고, 사용하는 곳이 많으면 반복적으로 선언해야 할텐데 뭐가 더 좋을까요?

2020-09-11 04:39 UTC, KueNiYam commented on front/src/component/mypage/MyProfile.js
> +  const setCurrentUser = useSetRecoilState(userState);
뭔가 규칙이 있으면 좋을 거 같은데..

2020-09-14 14:07 UTC, ParkDooWon reviewed
UserControllerTest에 header까지 추가해서 완벽한 피드백 반영이네요! 👍 
추가로 `src/docs/asciidocs` 아래에 `api-docs`파일에 만들어 둔 스니펫 정보들 작성해주시면 더욱 완벽할 것 같아요! :)

2020-09-15 11:48 UTC, ParkDooWon approved these changes
확인했습니다 작곰! approve하도록 할게요.
정말 수고하셨습니다!! 😄

2020-09-16 04:42 UTC, toneyparky approved these changes
요구사항 반영하느라 고생했어요 approve합니다~

2020-09-16 04:42 UTC, merged