Feat/252 Ingredient 도메인과 service, controller를 구현한다.
woowacourse-teams/2020-6rinkers pull request #254
Opened 2021-02-07 07:38 UTC by KimGyeong

resolve: #252 

---
테스트 코드는 컨트롤러 단위 테스트만 작성하였습니다.
추가적으로 id가 아닌, 이름으로 찾기도 구현할 필요가 있는 것 같아요. 
논의 한번 해봅시다.

2021-02-07 07:53 UTC, toneyparky requested changes
코멘트를 남겼습니당
외부이고 노트북이 없어서 돌려보질 못했네용
이야기 나눠보죠!

2021-02-07 07:53 UTC, toneyparky commented on back/cocktailpick-api/src/main/java/com/cocktailpick/api/config/security/SecurityConfig.java
> +			.hasRole(USER)
회의에서 유저도 재료를 생성할 수 있도록 열어주자 했었는가요
자료를 찾아봐도 안 나와있군용

2021-02-07 07:53 UTC, toneyparky commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/ingredient/controller/IngredientControllerTest.java
> +    void findIngredient() throws Exception {
Id로 조회한다는 내용이 들어가면 좋을 것 같습니다

2021-02-07 07:53 UTC, toneyparky commented on back/cocktailpick-api/src/main/java/com/cocktailpick/api/config/security/SecurityConfig.java
> +			.hasRole("ADMIN")
삭제에 대한 인가 설정이 없네유

2021-02-07 07:53 UTC, toneyparky commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/ingredient/docs/IngredientDocumentation.java
> +                        headerWithName("Location").description("생성된 재료 id")
아래는 ID고 여기만 id네요
뭐 이런거 까지 잡아봤습니다😬😬😬

2021-02-07 07:53 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/ingredient/domain/Ingredient.java
> +    private Double abv;
![image](https://user-images.githubusercontent.com/37579660/107140279-6958b780-6964-11eb-87f2-3c34619b653f.png)

Description이 있던 것 같은데 없어졌군요

근데 없어도 될거 같기도 하네용
이야기해보죠

2021-02-07 07:53 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/ingredient/service/IngredientService.java
> +    private Ingredient findById(Long id) {
Readonly 트랜젝셔널을 달면 좋을 것 같습니다

2021-02-07 07:59 UTC, toneyparky commented
이름으로 조회가 필요하려면 자동완성에 대한 니즈가 있어야겠다 싶네요.
혹은 이름으로 검색도요.

![image](https://user-images.githubusercontent.com/37579660/107140497-af624b00-6965-11eb-8994-4a5f6eb9ea1e.png)

요걸 봤을 때에 생성에는 필요가 없어보이지만
추후에 재료만으로 검색등을 할때에 필요할 수 있으니 만들죠!!

2021-02-07 07:59 UTC, toneyparky commented on back/cocktailpick-api/src/main/java/com/cocktailpick/api/config/security/SecurityConfig.java
> +			.hasRole(USER)
이건 열어주자고 했던 것 같네요!!

2021-02-07 14:53 UTC, KimGyeong commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/ingredient/service/IngredientService.java
> +    private Ingredient findById(Long id) {
private 메소드입니당
이 메소드 사용하는 메소드에 모두 transactional이 적용되어 있으니 상관없지 않을까요?

2021-02-07 14:53 UTC, KimGyeong commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/ingredient/docs/IngredientDocumentation.java
> +                        headerWithName("Location").description("생성된 재료 id")
어헣

2021-02-07 14:54 UTC, KimGyeong commented on back/cocktailpick-api/src/main/java/com/cocktailpick/api/config/security/SecurityConfig.java
> +			.hasRole("ADMIN")
후다닥 외출 준비하려고 하다보니 놓쳐버렸네요... 추가하였습니다.

2021-02-07 14:54 UTC, KimGyeong commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/ingredient/controller/IngredientControllerTest.java
> +    void findIngredient() throws Exception {
다른 도메인은 그렇게 되어 있지 않더라구용
일단 수정했는데 통일성에 대해 좀 고민해봐야겠습니다

2021-02-08 00:06 UTC, toneyparky commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/ingredient/controller/IngredientControllerTest.java
> +    void findIngredient() throws Exception {
오호 그렇군용
다른 데를 확인을 못해봤네요~
미안해요
이러면 다시 복구시키는 것이 나을 것 같다는 생각입니다.
제가 고칠게용

2021-02-08 00:07 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/ingredient/service/IngredientService.java
> +    private Ingredient findById(Long id) {
오 그러네요.
제가 놓쳤습니다.
그대로 가지요. 다만 추후에 public으로 바뀔 때에는 꼭 붙여주죠~

2021-02-08 00:09 UTC, toneyparky approved these changes
수고했습니다~
간만의 코딩 피알이네요 크크
바로 머지할게요

2021-02-08 00:15 UTC, merged