UserCocktail service, controller를 구현한다. (미완성)
woowacourse-teams/2020-6rinkers pull request #265
Opened 2021-02-22 23:58 UTC by KimGyeong

#262 
현재 생성, 단일 조회, 전체 조회까지 마쳤습니다.
만들고보니 완성된 아이템의 색상을 만드는 로직이 어디서 들어가야 할 지 논의를 해봐야겠단 생각이 드네요.
오늘 업데이트와 삭제가 완료될 예정입니다.

2021-02-23 00:35 UTC, toneyparky requested changes
고생했습니다~

몇가지 코멘트 남겼는데 이야기 나눠보아용~

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/usercocktail/dto/UserCocktailResponse.java
> +	private List<UserRecipeItemResponse> userRecipeItemResponses;
id 값도 넣어서 보내주는건 어떨까용?

전체조회에서 element를 클릭할 경우 상세조회를 할 경우에 필요할듯하네요~

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/userCocktail/controller/docs/UserCocktailDocumentation.java
> +				fieldWithPath("userCocktailResponses.[].description").type(JsonFieldType.STRING)
여기도 ID가 들어가겠죠?

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/usercocktail/dto/UserCocktailResponse.java
> +@NoArgsConstructor
```suggestion
@NoArgsConstructor(access = AccessLevel.PRIVATE)
```

access를 달아줄까용?

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/usercocktail/dto/UserCocktailCreateRequest.java
> +            userRecipeItems.add(userRecipeItemRequests.get(i).toUserRecipeItem(ingredients.get(i)));
```suggestion
            UserRecipeItem item = userRecipeItemRequests.get(i).toUserRecipeItem(ingredients.get(i))
            userRecipeItems.add(item);
```

요정도로 수정해서 가독성을 높혀도 좋을듯해요

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/usercocktail/dto/UserCocktailResponses.java
> +@NoArgsConstructor
```suggestion
@NoArgsConstructor(access = AccessLevel.PRIVATE)
```

😊

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/usercocktail/dto/UserRecipeItemResponse.java
> +@NoArgsConstructor
```suggestion
@NoArgsConstructor(access = AccessLevel.PRIVATE)
```
🙂

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/usercocktail/service/UserCocktailService.java
> +    public UserCocktailResponse findUserCocktail(Long id) {
@Transactional(readOnly = true)
붙여주죠!

2021-02-23 00:35 UTC, toneyparky commented on back/cocktailpick-core/src/main/java/com/cocktailpick/core/usercocktail/service/UserCocktailService.java
> +    public UserCocktailResponses findUserCocktails() {
여기도!

2021-02-23 16:55 UTC, KimGyeong commented
resolve: #262 
피드백 반영 후, 나머지 API를 구현해서 바로 푸쉬했습니다.

2021-02-24 00:37 UTC, toneyparky approved these changes
수고했습니다.
프론트에서 컴포넌트명 수정하는건 내가 할게용

2021-02-24 00:37 UTC, toneyparky commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/userCocktail/controller/controller/UserCocktailControllerTest.java
> +            .description("해피해킹 없이는 살 수 없는 몸이 돼었어")
?

2021-02-24 00:37 UTC, toneyparky commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/userCocktail/controller/controller/UserCocktailControllerTest.java
> +
공백이 있는데 내가 수정할겡

2021-02-24 00:41 UTC, KimGyeong commented on back/cocktailpick-api/src/test/java/com/cocktailpick/api/userCocktail/controller/controller/UserCocktailControllerTest.java
> +            .description("해피해킹 없이는 살 수 없는 몸이 돼었어")
들켰군

2021-02-25 14:26 UTC, merged